# Generated by Django 5.0.4 on 2024-06-04 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgrilandApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='')),
                ('Year', models.IntegerField()),
                ('Rating', models.IntegerField()),
            ],
        ),
    ]
