# Generated by Django 5.0.4 on 2024-06-11 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgrilandApp', '0005_product_is_sale_product_sale_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_homegrown',
            field=models.BooleanField(default=False),
        ),
    ]
