# Generated by Django 5.0.4 on 2024-06-12 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgrilandApp', '0006_product_is_homegrown'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='old_cart',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
