# Generated by Django 5.0.4 on 2024-06-13 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_remove_shippingaddress_phone_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='address1',
            new_name='ship_address1',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='address2',
            new_name='ship_address2',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='phone',
            new_name='ship_email',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='city',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='email',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='full_name',
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='ship_city',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='ship_full_name',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='ship_phone',
            field=models.CharField(default='', max_length=250),
        ),
    ]
