# Generated by Django 5.0.4 on 2024-06-15 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_order_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='shipping_address1',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='shipping_address2',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='shipping_city',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='shipping_email',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='shipping_full_name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='shipping_phone',
            field=models.CharField(max_length=250),
        ),
    ]
